// examples/frameworks/react/javascript/eventedit/src/App.js
/**
 * Application
 */
import React from 'react';
import { BryntumCalendar, BryntumDemoHeader } from '@bryntum/calendar-react';
import { calendarConfig } from './AppConfig';
import './App.scss';

function App() {

    return (
        <>
            {/* BryntumDemoHeader component is used for Bryntum example styling only and can be removed */}
            <BryntumDemoHeader />
            <BryntumCalendar
                {...calendarConfig}
            />
        </>
    );
}

export default App;

// examples/frameworks/vue-3/javascript/inline-data/src/App.vue
<!-- Application -->
<template>
    <!-- BryntumDemoHeader component is used for Bryntum example styling only and can be removed -->
    <bryntum-demo-header/>
    <bryntum-calendar
        ref="calendar"
        v-bind="calendarConfig"
        :events="events"
        :resources="resources"
    />
</template>

<script>
import { ref, reactive } from 'vue';

import {
    BryntumDemoHeader,
    BryntumCalendar
} from '@bryntum/calendar-vue-3';

import { useCalendarConfig } from '@/AppConfig';
import * as appData from '@/AppData';

export default {
    name: 'App',

    components: {
        BryntumDemoHeader,
        BryntumCalendar
    },

    setup() {
        const calendar = ref(null);

        const calendarConfig = reactive(useCalendarConfig());

        const events = ref(appData.events);
        const resources = ref(appData.resources);

        return {
            calendar,
            calendarConfig,
            events,
            resources
        };
    }
};
</script>

<style lang="scss">
@import './App.scss';
</style>
