// examples/frameworks/vue-3/javascript/undoredo/src/App.vue
<!-- Application -->
<template>
    <!-- BryntumDemoHeader component is used for Bryntum example styling only and can be removed -->
    <bryntum-demo-header/>
    <bryntum-calendar
        v-bind="calendarConfig"
    />
</template>

<script>

// app components
import {
    BryntumDemoHeader,
    BryntumCalendar
} from '@bryntum/calendar-vue-3';
import { calendarConfig } from '@/AppConfig';

export default {
    name: 'App',

    components: {
        BryntumDemoHeader,
        BryntumCalendar
    },

    setup() {
        return {
            calendarConfig
        };
    }
};
</script>

<style lang="scss">
@import './App.scss';
</style>

// examples/frameworks/react/javascript/eventedit/src/App.js
/**
 * Application
 */
import React from 'react';
import { BryntumCalendar, BryntumDemoHeader } from '@bryntum/calendar-react';
import { calendarConfig } from './AppConfig';
import './App.scss';

function App() {

    return (
        <>
            {/* BryntumDemoHeader component is used for Bryntum example styling only and can be removed */}
            <BryntumDemoHeader />
            <BryntumCalendar
                {...calendarConfig}
            />
        </>
    );
}

export default App;
